ALTER TABLE `ip_company` CHANGE COLUMN `CO_CODE` `CO_CODE` VARCHAR(30) NOT NULL;

ALTER TABLE `ip_company` ADD COLUMN `CO_DESC`  varchar(300) NULL COMMENT '描述' AFTER `IS_ENABLED`;

ALTER TABLE `ip_hirer` ADD COLUMN `LOGIN_NAME` VARCHAR(45) NULL COMMENT '登陆账号' AFTER `HIRER_PIC_URL`;

ALTER TABLE `ip_user` ADD COLUMN `EXTENSION` VARCHAR(45) NULL  AFTER `USER_PIC_URL` ;

ALTER TABLE `ip_company` ADD COLUMN `LEVEL_NUM`  int(2) NULL DEFAULT 1 COMMENT '部门级别' AFTER `CO_DESC`;

ALTER TABLE `ip_user` CHANGE COLUMN `GRADUATE_SCHOOLl` `GRADUATE_SCHOOL` VARCHAR(20) NULL DEFAULT NULL COMMENT '毕业学校'  ;

ALTER TABLE `ip_company` ADD COLUMN `DEPT_DETAIL` VARCHAR(300) NULL DEFAULT NULL  AFTER `LEVEL_NUM` ;

ALTER TABLE `ip_company` MODIFY COLUMN `LEVEL_NUM`  varchar(2) NULL DEFAULT '1' COMMENT '部门级别' AFTER `CO_DESC`;

ALTER TABLE `ip_user` CHANGE COLUMN `CELLPHONE_NO` `CELLPHONE_NO` VARCHAR(30) NULL DEFAULT NULL COMMENT '手机号码'  ;

ALTER TABLE `ip_menu` MODIFY COLUMN `URL`  varchar(200)  NULL DEFAULT NULL COMMENT '菜单URL' AFTER `IS_LEAF`;

ALTER TABLE `ip_user` MODIFY COLUMN `IS_ENABLED`  varchar(20) NULL DEFAULT '1' AFTER `CELLPHONE_NO`;

ALTER TABLE `ip_menu` ADD COLUMN `MENU_LOGO`  varchar(100) NULL COMMENT '菜单logo的，对应前端的class' AFTER `IS_JUMP`;

ALTER TABLE `ip_company` ADD COLUMN `DISP_ORDER`  varchar(10) NULL COMMENT '顺序序号' AFTER `DEPT_DETAIL`;

ALTER TABLE `ip_role` ADD COLUMN `DISP_ORDER`  varchar(10) NULL COMMENT '排序序号' AFTER `ROLE_DESC`;

ALTER TABLE `ip_user_role` ADD COLUMN `DISP_ORDER`  varchar(10) NULL COMMENT '排序序号,只对主职排序' AFTER `IS_PART_TIME`;

ALTER TABLE `ip_region` ADD COLUMN `UPDATE_DATE`  date NULL COMMENT '更新时间' AFTER `CREATE_DATE`;

ALTER TABLE `ip_company`
MODIFY COLUMN `LEVEL_NUM`  int(2) NULL DEFAULT 1 COMMENT '部门级别' AFTER `CO_DESC`,
MODIFY COLUMN `DISP_ORDER`  int(10) NULL DEFAULT 0 COMMENT '顺序序号' AFTER `DEPT_DETAIL`;

ALTER TABLE `ip_role`
MODIFY COLUMN `DISP_ORDER`  int(10) NULL DEFAULT 0 COMMENT '排序序号' AFTER `ROLE_DESC`;

ALTER TABLE `ip_user_role`
MODIFY COLUMN `DISP_ORDER`  int(10) NULL DEFAULT 0 COMMENT '排序序号' AFTER `IS_PART_TIME`;


update ip_company set DISP_ORDER=0 where DISP_ORDER is null;

update ip_role  set DISP_ORDER=0 where DISP_ORDER is null;

update ip_user_role set DISP_ORDER=0 where DISP_ORDER is null;


ALTER TABLE `ip_dictionary_detail` ADD COLUMN `detail_key`  varchar(60) NULL COMMENT '键值' AFTER `dic_id`;

ALTER TABLE `ip_dictionary_detail` ADD PRIMARY KEY (`the_id`);

ALTER TABLE `ip_user_company` MODIFY COLUMN `CO_CODE`  varchar(30) NOT NULL AFTER `CO_ID`;

